### ISSUE TITLE
Incorporate Mod1 into HTML5 port of Cossacks

### ISSUE THREAD

**Issue by GreenMouseFan** [klym1/Cossacks-on-Canvas#1]
Great work done here on this alpha test release.
I wonder, when a port of Cossacks for HTML5 Canvas will be finished, can be elements from Mod1 and Cossacks 3 be incorporated, such as new unique units for existing nations?
I want the game to be more unique, historically accurate.
The following new units are here in this list:

Algeria: Bashibozouk
Austria: 18c musketeer
Austria: Grenadier
Bavaria: Grenadier
Denmark: Grenadier
Netherlands: 18c musketeer
Netherlands: 18c dragoon
England: 17c pikeman
England: 17c musketeer
England: Rider
England: 17c dragoon
England: 18c musketeer
England: Grenadier
France: 17c pikeman
France: 17c musketeer
France: 18c musketeer
Hungary: Grenadier
Piedmont: 18c musketeer
Piedmont: 18c dragoon
Poland: 17c dragoon (Pospolite ruszenie)
Poland: Grenadier
Portugal: 18c musketeer
Portugal: 17c pikeman
Portugal: Volunteer
Prussia: Grenadier
Russia: 18c musketeer
Russia: Grenadier
Russia: Hussar
Sweden: 17c pikeman
Sweden: 17c musketeer
Sweden: 18c musketeer
Sweden: Grenadier
Sweden: 18c dragoon
Sweden: Hussar
Sweden: Light rider (Hakkapeliitta)
Spain: 18c dragoon
Spain: 17c pikeman (Cosolete)
Turkey: Ottoman (heavy) infantryman
Ukraine: Chaika ship
Venice: 17c musketeer
European 17c cannon (all nations except Algeria and Turkey)
Ottoman cannon (Algeria and Turkey)
Coastal defence cannon (all nations)

For units not present in Mod1, we can make new graphics for these units.

For Bavaria and Danmark, i think we should make new sprites for 18c musketeers and use the old sprites for grenadiers.

Scotland from CS3: Guardians of the Highlands DLC shall be added too with it's own architecture and unique units.

Please complete this port if possible?
Cuz I want to play Cossacks on modern PC with Windows 10 and with all the above new units.

![screen1](https://user-images.githubusercontent.com/80595517/111141454-2a96cc80-85b6-11eb-8b4a-19680036652c.jpg)
![screen2](https://user-images.githubusercontent.com/80595517/111141483-31254400-85b6-11eb-867e-33120215e8ad.jpg)
![screen3](https://user-images.githubusercontent.com/80595517/111141503-371b2500-85b6-11eb-8663-aa8dfb776750.jpg)
![screen39](https://user-images.githubusercontent.com/80595517/111141519-3c786f80-85b6-11eb-89a0-95371fda33c1.jpg)

**Comment by klym1** [comment]
OMG! Hello there @GreenMouseFan!
This project can hardly be named 'an alpha' or even 'html 5' Cossacks port. These were my poor attempts to recreate a sprite animation of some units. I didn't advance much, I've ended up with a horseman unit that can walk around the canvas and that's it :) 
I've abandoned this project many years ago and see no possibilities for further development. Sorry.
